name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행
  pull_request:
    branches:
      - main  # main 브랜치로 PR이 생성될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 지정

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 환경 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 의존성 설치
        run: pip install -r requirements.txt

      - name: 코드 빌드
        run: python setup.py build

  test:
    runs-on: ubuntu-latest
    needs: build  # 빌드가 성공해야 실행됨

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 환경 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 의존성 설치
        run: pip install -r requirements.txt

      - name: 테스트 실행
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test  # 테스트가 성공해야 실행됨

    steps:
      - name: 배포 스크립트 실행
        run: echo "Deploying the application..."
